### ISSUE TITLE
Dir.glob too liberal when no lib folder

### ISSUE THREAD

**Issue by techbelly** [lazyatom/gem-this#2]
If there's no lib folder in the folder in which you run 'gem this' s.files gets set to something like Dir.glob("{}/*_/_"). Then, when you run rake s.files will get set to every file on your machine - or least rake will hang until it runs out of memory.

**Comment by lazyatom** [comment]
Fixed glob so that if none of the expected directories are there, the
Rakefile doesn't crap out. Closed by cb86401d2f251576db193621133379c00eb26556
