### ISSUE TITLE
compatibility with new rubygems?

### ISSUE THREAD

**Issue by matthewrudy** [lazyatom/gem-this#5]
So it seems the rapid changes to rubygems have rendered gem-this invalid.

```
RudiMac:rcov_rails matthew$ rake package
rake/gempackagetask is deprecated.  Use rubygems/package_task instead
rake/rdoctask is deprecated.  Use rdoc/task instead (in RDoc 2.4.2+)
NOTE: Gem::Specification#has_rdoc= is deprecated with no replacement. It will be removed on or after 2011-10-01.
Gem::Specification#has_rdoc= called from /Users/matthew/code/rcov_rails/Rakefile:25
```

The offending lines in my gemspec are

```
require "rake/gempackagetask"
require "rake/rdoctask"

spec = Gem::Specification.new do |s|
  ...
  s.has_rdoc          = true
  s.extra_rdoc_files  = %w(README)
  s.rdoc_options      = %w(--main README)
  ...
end

Rake::GemPackageTask.new(spec) do |pkg|
  pkg.gem_spec = spec
end
```

I'm ignoring the rdoc stuff for now.
And will instead attempt to fix the gem package stuff

Changing the require, and the task class seems to work.

```
require "rubygems/package_task"

Gem::PackageTask.new(spec) do |pkg|
  pkg.gem_spec = spec
end
```

But who knows if this will work in a couple of months time.

**Comment by lazyatom** [comment]
Hmm, interesting. I will investigate.

**Comment by matthewrudy** [comment]
I think it may be worth waiting until the war of Rubygems settles down.
But there are definitely a few changes that need to be made if rubygems keeps down its >1.7 route.

Exciting times!

**Comment by matthewrudy** [comment]
It seems actually that this is to do with the new version of rake.
In particular, upgrading my rails 2.3 project to rake 0.9.2 caused similar problems

**Comment by lazyatom** [comment]
Yeah - looks like this is just a rake deprecation thing.

Fixed in 58e15684e0c0f81c25684bc572bfc97f2859b495

On 9 June 2011 06:50, matthewrudy
reply@reply.github.com
wrote:

**Comment by lazyatom** [comment]
I've just pushed 0.3.7, which includes this fix. Thanks!

**Comment by matthewrudy** [comment]
Works for me.
Interestingly when you run the `rake package` command on old rubygems you get a helpful;

```
$ rake package
mv rcov_rails-0.3.1.gem ..
$ ...
```

which seems to have been a bug.

but in the new rubygems (I'm testing on 1.8.5)
we get nothing (maybe I prefer the bug)

```
$ rake package
$ ...
```

looking at the source of the package task it will only be verbose if you pass in a rake --trace

```
$ rake --trace package
... too much mess ...
Successfully built RubyGem
Name: rcov_rails
Version: 0.3.1
File: rcov_rails-0.3.1.gem
... more mess ...
$
```
